export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS"
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL"
export const GET_ALL_USER_LOADING = "GET_ALL_USER_LOADING"

export const GET_ALL_LAWYER_SUCCESS = "GET_ALL_LAWYER_SUCCESS"
export const GET_ALL_LAWYER_FAIL = "GET_ALL_LAWYER_FAIL"
export const GET_ALL_LAWYER_LOADING = "GET_ALL_LAWYER_LOADING"

export const GET_ALL_CLIENT_SUCCESS = "GET_ALL_CLIENT_SUCCESS"
export const GET_ALL_CLIENT_FAIL = "GET_ALL_CLIENT_FAIL"
export const GET_ALL_CLIENT_LOADING = "GET_ALL_CLIENT_LOADING"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS"
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL"