export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS"
export const POST_PROFILE_FAIL = "POST_PROFILE_FAIL"

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"