export const GET_ALL_LAWYER_GUEST_SUCCESS = "GET_ALL_LAWYER_GUEST_SUCCESS"
export const GET_ALL_LAWYER_GUEST_FAIL = "GET_ALL_LAWYER_GUEST_FAIL"
export const GET_ALL_LAWYER_GUEST_LOADING = "GET_ALL_LAWYER_GUEST_LOADING"

export const GET_ONE_LAWYER_GUEST_SUCCESS = "GET_ONE_LAWYER_GUEST_SUCCESS"
export const GET_ONE_LAWYER_GUEST_FAIL = "GET_ONE_LAWYER_GUEST_FAIL"